In [2]:
import torch.nn as nn
from PIL import Image
import cv2
import torch
import torch.nn.functional as F
import numpy as np

In [3]:
grid = np.arange(32)

In [4]:
a, b = np.meshgrid(grid, grid)
a.shape

(32, 32)

In [5]:
x_offset = torch.FloatTensor(a).view(-1, 1)
y_offset = torch.FloatTensor(b).view(-1, 1)

In [6]:
x_offset, x_offset.size()

(tensor([[ 0.],
         [ 1.],
         [ 2.],
         ...,
         [29.],
         [30.],
         [31.]]),
 torch.Size([1024, 1]))

In [7]:
y_offset

tensor([[ 0.],
        [ 0.],
        [ 0.],
        ...,
        [31.],
        [31.],
        [31.]])

In [8]:
b

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 1,  1,  1, ...,  1,  1,  1],
       [ 2,  2,  2, ...,  2,  2,  2],
       ...,
       [29, 29, 29, ..., 29, 29, 29],
       [30, 30, 30, ..., 30, 30, 30],
       [31, 31, 31, ..., 31, 31, 31]])

In [9]:
a

array([[ 0,  1,  2, ..., 29, 30, 31],
       [ 0,  1,  2, ..., 29, 30, 31],
       [ 0,  1,  2, ..., 29, 30, 31],
       ...,
       [ 0,  1,  2, ..., 29, 30, 31],
       [ 0,  1,  2, ..., 29, 30, 31],
       [ 0,  1,  2, ..., 29, 30, 31]])

In [10]:
c = torch.cat((x_offset, y_offset), 1)
c

tensor([[ 0.,  0.],
        [ 1.,  0.],
        [ 2.,  0.],
        ...,
        [29., 31.],
        [30., 31.],
        [31., 31.]])

In [11]:
d = c.repeat(1, 3)

In [12]:
d, d.size()

(tensor([[ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 1.,  0.,  1.,  0.,  1.,  0.],
         [ 2.,  0.,  2.,  0.,  2.,  0.],
         ...,
         [29., 31., 29., 31., 29., 31.],
         [30., 31., 30., 31., 30., 31.],
         [31., 31., 31., 31., 31., 31.]]),
 torch.Size([1024, 6]))

In [13]:
e = d.view(-1, 2)

In [14]:
e.size()

torch.Size([3072, 2])

In [15]:
e

tensor([[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        ...,
        [31., 31.],
        [31., 31.],
        [31., 31.]])

In [16]:
e[0:10]

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [2., 0.],
        [2., 0.],
        [2., 0.],
        [3., 0.]])

In [17]:
f = e.unsqueeze(0)

In [18]:
f.size()

torch.Size([1, 3072, 2])

In [19]:
anchors = [[10,13],  [16,30],  [33,23]]
anchors_ = [(a[0]/32, a[1]/32) for a in anchors]
anchors__ = torch.FloatTensor(anchors_).repeat(32*32, 1)

In [20]:
anchors__, anchors__.size()

(tensor([[0.3125, 0.4062],
         [0.5000, 0.9375],
         [1.0312, 0.7188],
         ...,
         [0.3125, 0.4062],
         [0.5000, 0.9375],
         [1.0312, 0.7188]]),
 torch.Size([3072, 2]))

In [21]:
a = [[1, 2], [3, 4]]

In [22]:
a *= 2

In [23]:
a

[[1, 2], [3, 4], [1, 2], [3, 4]]

In [32]:
img = Image.open('./imgs/bus.jpg')

In [35]:
img_ = img.resize((540, 405))

In [38]:
img.size, img_.size

((810, 1080), (540, 405))

In [39]:
img.show()

In [40]:
img_.show()

In [28]:
cv2.imshow('', img_)
cv2.waitKey(0)

-1